### PR TITLE
Add nuvoton target dependency

### PR DESCRIPTION
**Pull request by cyliangtw**
This is Nuvoton PR for adding mbed-hal-nuvoton module into module.json .
```
    "cordio": {
      "mbed-hal-cordio": "~0.0.5"
    },
    "nuvoton": {
      "mbed-hal-nuvoton": "^1.0.0"
    }
```

### CODE REVIEW

**Comment by cyliangtw** [comment]
The failing check revealed verification build failure in mkit-gcc. I just added “Add nuvoton target dependency" in module.json, I can't realize how could it affect mkit-gcc target ?

**Comment by 0xc0170** [comment]
Hi, I can't locate mbed-hal-nuvoton module in yotta registry (other modules might be as well private).

I triggered a new build, mkit failure was not caused by this change-set

**Comment by cyliangtw** [comment]
Thanks of your clarification, mbed-hal-nuvoton relative modules are still private. For proceeding PR #62, could I ignore this "verification build failure" or what action should I take ?

**Comment by 0xc0170** [comment]
@cyliangtw How can we get an access for those modules? To be able to review. If there are private on github, can you add me to have an access?

**Comment by cyliangtw** [comment]
Hi Martin, I already added you to have access permission of nuc472 or nuvoton relative modules.

**Comment by 0xc0170** [comment]
@cyliangtw Thanks. I had a look. In general, they look good to me. I'll talk to the team and get back to you soon.

**Pull request merged**
