### PR TITLE
Fix support of legacy targets (without yotta config pin definitions)

### PR DESCRIPTION
**Pull request by bremoran**
This PR is part of fixing support for legacy targets that use yotta config pin definitions.

Renaming PinNames.h allows the relevant ```mbed-hal-<vendor>-<chip>``` module to define PinNames.h, which will simply include GeneratedPinNames.h.  This will keep compatibility until legacy targets can be updated.  Once that has been done, PinNames.h can be moved into ```mbed-hal```

### CODE REVIEW

**Comment by bremoran** [comment]
cc @0xc0170 @bogdanm

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by autopulated** [comment]
+1

**Comment by 0xc0170** [comment]
LGTM

Seems we might have missed some files in platforms, an example - https://github.com/ARMmbed/mbed-hal-frdm-k64f/blob/master/mbed-hal-frdm-k64f/PinNames.h . This should be removed

**Pull request merged**
