### PR TITLE
Readme - add API description

### LINKED ISSUE #40: readme has several "TBC" sections

### PR DESCRIPTION
**Pull request by 0xc0170**
Once complete, this should fix #40

I would like to gather some input what should be in here instead of TBC plus the description of this module. I was not certain of Usage for this module, thus removed.

Please leave the comment or talk to me.

@bremoran @autopulated @bogdanm @niklas-arm

### CODE REVIEW

**Comment by autopulated** [comment]
LGTM – I'd make this warning bigger though / warn that people should avoid depending on it directly:

> mbed hal API is considered an internal interface. We are planning to improve mbed-hal in the future, which might require changes in API.

:grinning:

**Comment by 0xc0170** [comment]
The warning note is now with strong emphasis - bold.

**Comment by 0xc0170** [comment]
Bump

**Comment by autopulated** [comment]
lgtm

**Comment by niklas-arm** [comment]
:+1:

**Pull request merged**
