### PR TITLE
ripple from having updated version for mbed-hal-nordic

### PR DESCRIPTION
**Pull request by rgrover**
@0xc0170 @bogdanm @autopulated

### CODE REVIEW

**Comment by rgrover** [comment]
please review this for a minor version bump.
@0xc0170 @bogdanm @autopulated

**Comment by 0xc0170** [comment]
LGTM, will release a new minor version later, first patch with all those docs fixes

**Comment by 0xc0170** [comment]
I have to rerun tests here.  I pulled the sources, can't compile and there's yotta error. I'll paste here the error if I am not able to rerun jenkins for this PR

**Comment by rgrover** [comment]
Thanks @0xc0170. Please paste the error. @andresag01  and I are eager to have this resolved.

**Comment by andresag01** [comment]
@0xc0170 The problem is that we are changing the place where the pin names for P0_(0-30) are defined. We are moving them from the nrf51 targets into the mbed-hal-nrf51822-mcu module. However, because this pull request had not gone through we had to revert the changes since yotta would pull the wrong version of mbed-hal-nrf51822-mcu and then no pins would be defined at all. Once this pull request is merged then I will updated the following targets again:

* target-nrf51dk-gcc
* target-nrf51dk-armcc
* target-mkit-gcc
* target-mkit-armcc
* target-bbc-microbit-gcc
* target-bbc-microbit-armcc

**Comment by rgrover** [comment]
published

**Comment by 0xc0170** [comment]
mkit armcc builds locally with the latest mkit armcc target.

**Pull request merged**
